spring:
  application:
    name: chengxin-insurance-consumer-dev

server:
  port: 8082

chengxin:
  service:
    version: 1.0.2
dubbo:
  application:
    id: chengxin-insurance-consumer-dev
    name: chengxin-insurance-consumer-dev
  registry:
    protocol: zookeeper
#    address: 127.0.0.1:2181
    address: 47.106.184.234:2181
    id: chengxin-registry-dev
  consumer:
    check: false

management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true

  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'



apps:
  common:
     attachment:
        url: http://127.0.0.1:82/chengxin
        path: D:/software/nginx/html/chengxin
     productH5Url: http://127.0.0.1:82/choose?prodductId=