
dubbo:
  application:
      name: chengxin-insurance-provider-dev
      id: chengxin-insurance-provider-dev
      qos-enable: true
      qos-port: 99999
  registry:
    protocol: zookeeper
#    address: 127.0.0.1:2181
    address: 47.106.184.234:2181
    id: chengxin-registry-dev
  protocol:
    port: 23466
    name: dubbo
    id: dubbo
    status: server
  consumer:
    check: false
  provider:
    delay: -1
    timeout: 3000
    retries: 0


  scan:
    basePackages: com.kingyon.chengxin.*.service
chengxin:
  service:
    version: 1.0.2

server:
  port: 9090

spring:
  application:
        name: chengxin-insurance-provider-dev

  datasource:
        name: db
        type: com.alibaba.druid.pool.DruidDataSource
    #    name: cwwyw
        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://47.106.219.95:3306/cxmedical_db_dev?useUnicode=true&characterEncoding=utf-8
        url: jdbc:mysql://47.106.184.234:3306/cxmedical_db?useUnicode=true&characterEncoding=utf-8
        username: root
        password: BoYaWM!123

    #    # 下面为连接池的补充设置，应用到上面所有数据源中
    #    # 初始化大小，最小，最大
        initialSize: 10
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 300000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 600000
        #validationQuery: select "1"
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

#        validationQuery: select 'x'
#        removeAbandoned: true

        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true


mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:/mappers/**/*.xml
  typeAliasesPackage: com.kingyon.chengxin.*


druid:
   loginUsername: admin
   loginPassword: 123456
   resetEnable: false

apps:
  common:
     openTest: true    # true 开启测试 ,false 关闭测试




